definitions:
  proto.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  proto.LoginResp:
    properties:
      token:
        type: string
      user_id:
        type: integer
    type: object
  proto.SignUpArgs:
    properties:
      email:
        description: 注册邮箱
        type: string
      facebook_id:
        description: facebook的三方账号
        type: string
      gooleplus_id:
        description: google+的三方账号
        type: string
      password:
        description: 用户密码
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
paths:
  /account/login:
    post:
      description: 账号登录
      parameters:
      - description: 账号登录
        in: body
        name: loginReq
        required: true
        schema:
          $ref: '#/definitions/proto.LoginReq'
      responses:
        "200":
          description: 登录tk
          schema:
            $ref: '#/definitions/proto.LoginResp'
      summary: 账号登录
      tags:
      - account
  /account/sign_up:
    post:
      description: 注册账号
      parameters:
      - description: 注册账号
        in: body
        name: signInArgs
        required: true
        schema:
          $ref: '#/definitions/proto.SignUpArgs'
      responses:
        "200":
          description: 登录tk
          schema:
            $ref: '#/definitions/proto.LoginResp'
      summary: 注册账号
      tags:
      - account
swagger: "2.0"
