version: '3'
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  # consul:
  #   image: consul
  #   ports:
  #   - "8500:8500"
  mysql:
    image: mysql:5.7.16
    container_name: mysql
    restart: always
    expose:
     - "3306"
    ports:
     - "3306:3306"
    environment:
      MYSQL_USER: "root"
      # So you don't have to use root, but you can if you like
      MYSQL_ROOT_PASSWORD: "root"
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: unit_test
  #mongo:
  #  image: mongo:4.0
  #  ports:
  #  - "27017:27017"
